<section class="surface overflow-hidden">
    <div class="border-b border-line px-5 py-4"><h2 class="section-title">Papelera</h2><p class="mt-1 text-sm text-muted">Restaura lo que necesites. No eliminamos contenido definitivamente desde este módulo.</p></div>
    @if($notice)<div class="mx-5 mt-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200" role="status">{{ $notice }}</div>@endif
    <div class="grid divide-y divide-line lg:grid-cols-3 lg:divide-x lg:divide-y-0">
        <div class="p-5"><h3 class="text-xs font-black uppercase tracking-[.16em] text-muted">Cuadernos</h3><div class="mt-3 space-y-2">@forelse($notebooks as $notebook)<div class="rounded-xl bg-surface-soft p-3"><p class="truncate font-bold text-ink">{{ $notebook->name }}</p><button type="button" wire:click="restoreNotebook({{ $notebook->id }})" class="mt-2 text-xs font-bold text-brand hover:underline">Restaurar</button></div>@empty<p class="py-5 text-sm text-muted">No hay cuadernos eliminados.</p>@endforelse</div>@if($notebooks->hasPages())<div class="mt-3">{{ $notebooks->links() }}</div>@endif</div>
        <div class="p-5"><h3 class="text-xs font-black uppercase tracking-[.16em] text-muted">Secciones</h3><div class="mt-3 space-y-2">@forelse($sections as $section)<div class="rounded-xl bg-surface-soft p-3"><p class="truncate font-bold text-ink">{{ $section->name }}</p><p class="mt-1 truncate text-xs text-muted">{{ $section->notebook?->name }}</p><button type="button" wire:click="restoreSection({{ $section->id }})" class="mt-2 text-xs font-bold text-brand hover:underline">Restaurar con páginas</button></div>@empty<p class="py-5 text-sm text-muted">No hay secciones eliminadas.</p>@endforelse</div>@if($sections->hasPages())<div class="mt-3">{{ $sections->links() }}</div>@endif</div>
        <div class="p-5"><h3 class="text-xs font-black uppercase tracking-[.16em] text-muted">Páginas</h3><div class="mt-3 space-y-2">@forelse($pages as $page)<div class="rounded-xl bg-surface-soft p-3"><p class="truncate font-bold text-ink">{{ trim((string) $page->title) ?: 'Página sin título' }}</p><p class="mt-1 truncate text-xs text-muted">{{ $page->section?->notebook?->name }} · {{ $page->section?->name }}</p><button type="button" wire:click="restorePage({{ $page->id }})" class="mt-2 text-xs font-bold text-brand hover:underline">Restaurar</button></div>@empty<p class="py-5 text-sm text-muted">No hay páginas eliminadas.</p>@endforelse</div>@if($pages->hasPages())<div class="mt-3">{{ $pages->links() }}</div>@endif</div>
    </div>
</section>
