<div wire:poll.60s>
    <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div><p class="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-brand">Operación recurrente</p><h1 class="text-2xl font-black tracking-tight text-ink sm:text-4xl">Servicios contratados</h1><p class="mt-2 max-w-2xl text-sm text-muted">Administra los servicios activos, su facturación y proveedor desde un solo lugar.</p></div>
        <a href="{{ route('contracted-services.create') }}" class="button w-full sm:w-auto">＋ Nuevo servicio</a>
    </div>

    <div class="mb-5 grid gap-5 lg:grid-cols-[minmax(0,1.1fr)_minmax(360px,0.9fr)] lg:items-start">
        <div class="panel lg:sticky lg:top-24">
            <div class="mb-4"><p class="text-xs font-bold uppercase tracking-[0.16em] text-brand">Filtros</p><h2 class="mt-1 text-lg font-black text-ink">Buscar y segmentar</h2><p class="mt-1 text-sm text-muted">Combina los criterios para actualizar los indicadores y el detalle.</p></div>
            <div class="grid gap-3">
                <label class="relative"><span class="sr-only">Buscar</span><span class="pointer-events-none absolute left-3 top-3 text-lg text-muted">⌕</span><input wire:model.live.debounce.300ms="search" class="input mt-0 pl-10" placeholder="Cliente, servicio o IP..."></label>
                <select wire:model.live="status" class="input mt-0"><option value="all">Todos los estados</option><option value="active">Activos</option><option value="cancelled">Cancelados</option></select>
                <select wire:model.live="provider" class="input mt-0"><option value="all">Todos los proveedores</option>@foreach($providers as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select>
                <div class="grid grid-cols-2 gap-3"><select wire:model.live="billingDayFrom" class="input mt-0"><option value="all">Día desde</option>@for($day = 1; $day <= 31; $day++)<option value="{{ $day }}">Desde {{ $day }}</option>@endfor</select><select wire:model.live="billingDayTo" class="input mt-0"><option value="all">Día hasta</option>@for($day = 1; $day <= 31; $day++)<option value="{{ $day }}">Hasta {{ $day }}</option>@endfor</select></div>
                <button wire:click="clearFilters" class="button-secondary w-full">Limpiar filtros</button>
            </div>
            <div wire:loading class="mt-3 text-xs font-semibold text-brand">Actualizando resultados…</div>
        </div>

        <div class="grid h-full gap-3 lg:grid-rows-4">
            <div class="card flex flex-col justify-center border-brand/20 bg-brand/[0.03] p-4"><p class="text-[11px] font-bold uppercase tracking-[0.16em] text-muted">Ingresos mensuales</p><p class="mt-1 text-xl font-black text-brand">USD {{ number_format($monthlyRevenue, 2) }}</p><p class="mt-1 text-[11px] text-muted">Según filtros activos</p></div>
            <div class="card flex flex-col justify-center p-4"><p class="text-[11px] font-bold uppercase tracking-[0.16em] text-muted">Costos mensuales</p><p class="mt-1 text-xl font-black text-ink">USD {{ number_format($monthlyCosts, 2) }}</p><p class="mt-1 text-[11px] text-muted">Costo de proveedores</p></div>
            <div class="card flex flex-col justify-center p-4"><p class="text-[11px] font-bold uppercase tracking-[0.16em] text-muted">Beneficio mensual</p><p class="mt-1 text-xl font-black {{ $monthlyProfit >= 0 ? 'text-emerald-700 dark:text-emerald-300' : 'text-red-600 dark:text-red-300' }}">USD {{ number_format($monthlyProfit, 2) }}</p><p class="mt-1 text-[11px] text-muted">Ingresos menos costos</p></div>
            <div class="card flex flex-col justify-center p-4"><p class="text-[11px] font-bold uppercase tracking-[0.16em] text-muted">Servicios activos</p><p class="mt-1 text-xl font-black text-ink">{{ $activeCount }}</p><p class="mt-1 text-[11px] text-muted">Coinciden con el filtro</p></div>
        </div>
    </div>

    <div class="surface overflow-hidden">
        <div class="hidden overflow-x-auto md:block"><table class="table"><thead><tr><th>Cliente</th><th>Servicio</th><th>IP</th><th>Estado</th><th>Mensualidad</th><th>Proveedor</th><th></th></tr></thead><tbody>@forelse($services as $service)<tr><td><p class="font-bold text-ink">{{ $service->client->name }}</p><p class="text-xs text-muted">Cobro día {{ $service->billing_day }}</p></td><td><p class="font-semibold text-ink">{{ $service->catalogService->name }}</p><p class="text-xs text-muted">Desde {{ $service->starts_at->format('d/m/Y') }}</p></td><td class="font-mono text-xs">{{ $service->ip ?: '—' }}</td><td><span class="rounded-full px-2.5 py-1 text-[10px] font-black uppercase {{ $service->status->value === 'active' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300' : 'bg-slate-100 dark:bg-slate-800 dark:text-slate-300' }}">{{ $service->status->value === 'active' ? 'Activo' : 'Cancelado' }}</span></td><td class="font-bold text-ink">{{ $service->price_currency }} {{ number_format($service->price, 2) }}</td><td class="text-sm text-muted">{{ $service->provider->name }}</td><td class="whitespace-nowrap"><a class="font-bold text-brand hover:underline" href="{{ route('contracted-services.edit', $service) }}">Editar</a><form class="ml-3 inline" method="post" action="{{ route('contracted-services.destroy', $service) }}">@csrf @method('delete')<button class="font-bold text-red-600 hover:underline" onclick="return confirm('¿Eliminar este servicio contratado?')">Borrar</button></form></td></tr>@empty<tr><td colspan="7" class="py-12 text-center text-muted">No encontramos servicios con esos filtros.</td></tr>@endforelse</tbody></table></div>
        <div class="divide-y divide-line md:hidden">@forelse($services as $service)<article class="p-4"><div class="flex items-start justify-between gap-3"><div><p class="font-bold text-ink">{{ $service->client->name }}</p><p class="text-sm text-muted">{{ $service->catalogService->name }}</p></div><span class="rounded-full px-2 py-1 text-[10px] font-black uppercase {{ $service->status->value === 'active' ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $service->status->value === 'active' ? 'Activo' : 'Cancelado' }}</span></div><div class="mt-4 grid grid-cols-2 gap-3 text-sm"><div><p class="text-xs text-muted">IP</p><p class="font-mono text-ink">{{ $service->ip ?: '—' }}</p></div><div><p class="text-xs text-muted">Mensualidad</p><p class="font-bold text-ink">{{ $service->price_currency }} {{ number_format($service->price, 2) }}</p></div><div><p class="text-xs text-muted">Proveedor</p><p class="text-ink">{{ $service->provider->name }}</p></div><div><p class="text-xs text-muted">Cobro</p><p class="text-ink">Día {{ $service->billing_day }}</p></div></div><div class="mt-4 flex items-center justify-between gap-3"><a class="font-bold text-brand" href="{{ route('contracted-services.edit', $service) }}">Editar servicio →</a><form method="post" action="{{ route('contracted-services.destroy', $service) }}">@csrf @method('delete')<button class="font-bold text-red-600" onclick="return confirm('¿Eliminar este servicio contratado?')">Borrar</button></form></div></article>@empty<div class="p-10 text-center text-muted">No encontramos servicios con esos filtros.</div>@endforelse</div>
        <div class="border-t border-line px-4 py-3">{{ $services->links() }}</div>
    </div>
</div>
