@extends('layouts.app')
@section('content')
<div class="mb-6"><p class="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-brand">Configuración</p><h1 class="text-2xl font-black tracking-tight text-ink sm:text-4xl">Datos de la empresa</h1><p class="mt-2 max-w-2xl text-sm text-muted">Esta información aparecerá como encabezado en tus cotizaciones y facturas.</p></div>
<form class="panel max-w-5xl space-y-6" method="post" action="{{ route('settings.company.update') }}" enctype="multipart/form-data">@csrf @method('put')
    <section><h2 class="section-title">Identidad comercial</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label>Nombre de la empresa<input class="input" name="company_name" value="{{ old('company_name', $settings->company_name) }}" placeholder="Ej. VicidialHosted"></label><label>Sitio web<input class="input" type="url" name="website" value="{{ old('website', $settings->website) }}" placeholder="https://ejemplo.com"></label><label>Correo electrónico<input class="input" type="email" name="email" value="{{ old('email', $settings->email) }}"></label><label>Teléfono<input class="input" name="phone" value="{{ old('phone', $settings->phone) }}"></label><label>Identificación fiscal<input class="input" name="tax_id" value="{{ old('tax_id', $settings->tax_id) }}"></label><label>Logo<input class="input" type="file" name="logo" accept="image/png,image/jpeg,image/webp,image/svg+xml"><span class="mt-1 block text-xs text-muted">PNG, JPG, WEBP o SVG. Máximo 2 MB.</span></label></div></section>
    <section class="border-t border-line pt-6"><h2 class="section-title">Dirección</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label class="md:col-span-2">Dirección<input class="input" name="address" value="{{ old('address', $settings->address) }}" placeholder="Calle, número, residencial o sector"></label><label>Ciudad<input class="input" name="city" value="{{ old('city', $settings->city) }}"></label><label>Provincia / estado<input class="input" name="province" value="{{ old('province', $settings->province) }}"></label><label>Código postal<input class="input" name="postal_code" value="{{ old('postal_code', $settings->postal_code) }}"></label><label>País<input class="input" name="country" value="{{ old('country', $settings->country) }}"></label></div></section>
    <section class="border-t border-line pt-6"><h2 class="section-title">Zona horaria</h2><div class="mt-4 max-w-xl"><label>Zona horaria para seguimiento<select class="input" name="timezone" required><option value="America/Santo_Domingo" @selected(old('timezone', $settings->timezone ?: 'America/Santo_Domingo') === 'America/Santo_Domingo')>República Dominicana (UTC-4)</option><option value="UTC" @selected(old('timezone', $settings->timezone) === 'UTC')>UTC</option><option value="America/New_York" @selected(old('timezone', $settings->timezone) === 'America/New_York')>Nueva York (UTC-5/-4)</option></select><span class="mt-1 block text-xs text-muted">Define cuándo comienzan y terminan los días operativos del módulo Seguimiento.</span></label></div></section>
    @if($settings->logo_path)<div class="rounded-xl border border-line bg-surface-soft p-4"><p class="mb-2 text-xs font-bold uppercase tracking-wider text-muted">Logo actual</p><img class="max-h-24 max-w-xs object-contain" src="{{ route('settings.company.logo') }}" alt="Logo de {{ $settings->company_name }}"></div>@endif
    <button class="button">Guardar configuración</button>
</form>
@endsection
